substitutions:
  name: abl-emh1
  device_description: "Monitor and configure ABL eMH1 Charger via RS485/Modbus-ASCII"
  external_components_source: github://jrv/esphome-abl-emh1
  tx_pin: "16"
  rx_pin: "17"
  flow_control_pin: "5"

esphome:
  name: ${name}
  comment: ${device_description}
  friendly_name: ABL eMH1 Charger
  project:
    name: "jrv.esphome-abl-emh1"
    version: 0.0.1

esp32:
  board: esp32dev

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  password: !secret ota_password

logger:
  level: DEBUG

# If you use Home Assistant please remove this `mqtt` section and uncomment the `api` component!
# The native API has many advantages over MQTT: https://esphome.io/components/api.html#advantages-over-mqtt
# mqtt:
#   broker: !secret mqtt_host
#  username: !secret mqtt_username
#  password: !secret mqtt_password
#  id: mqtt_client

api:
  encryption:
    key: !secret api_key

uart:
  id: uart_0
  baud_rate: 9600
  tx_pin: ${tx_pin}
  rx_pin: ${rx_pin}

emh1_modbus:
    uart_id: uart_0
    flow_control_pin: ${flow_control_pin}
    id: modbus0

abl_emh1:
  emh1_modbus_id: modbus0
  update_interval: 1s

text_sensor:
  - platform: abl_emh1
    mode_name:
      name: "${name} mode name"
    errors:
      name: "${name} errors"

sensor:
  - platform: abl_emh1
    l1_current:
      name: "${name} L1 current"
    l2_current:
      name: "${name} L2 current"
    l3_current:
      name: "${name} L3 current"
    max_current:
      name: "${name} Max current"
    serial_number:
      name: "${name} Serial number"
    outlet_state:
      name: "${name} Outlet state"
